spring:

  application:
    name: feleck
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

    database: mysql


  datasource:
    hikari:
      maximum-pool-size: 4
      url:
      username:
      password:
